version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    build:
      context: ./my-vanthkrab-nest
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/myapp_db?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./my-vanthkrab-nest:/app
      - /app/node_modules
    networks:
      - app-network
    command: sh -c "npx prisma db push && npm run start:prod"

  prisma-studio:
    build:
      context: ./my-vanthkrab-nest
      dockerfile: Dockerfile
    container_name: prisma_studio
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/myapp_db?schema=public
    depends_on:
      - postgres
    volumes:
      - ./my-vanthkrab-nest:/app
      - /app/node_modules
    networks:
      - app-network
    command: npx prisma studio --hostname 0.0.0.0

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge